### ISSUE TITLE
KeyError 0

### ISSUE THREAD

**Issue by TheBlizWiz** [misterhay/VISCA-IP-Controller#13]
I have my camera plugged in my ethernet cable port, and I'm running the default test program. I keep getting this error and I don't know what it means.

Traceback (most recent call last):
  File "D:\Church Camera Python Controller\VISCATEST.py", line 4, in <module>
    cam = Camera('169.254.138.106')  # Your camera's IP address or hostname here
  File "C:\Users\thebl\AppData\Local\Programs\Python\Python310\lib\site-packages\visca_over_ip\camera.py", line 31, in __init__
    self._send_command('00 01')  # clear the camera's interface socket
  File "C:\Users\thebl\AppData\Local\Programs\Python\Python310\lib\site-packages\visca_over_ip\camera.py", line 57, in _send_command
    response = self._receive_response()
  File "C:\Users\thebl\AppData\Local\Programs\Python\Python310\lib\site-packages\visca_over_ip\camera.py", line 88, in _receive_response
    raise ViscaException(response_payload)
  File "C:\Users\thebl\AppData\Local\Programs\Python\Python310\lib\site-packages\visca_over_ip\exceptions.py", line 14, in __init__
    self.description = descriptions[self.status_code]
KeyError: 0

**Comment by misterhay** [comment]
My guess is that your camera IP address isn't (or shouldn't be) `169.254.138.106`. The camera's IP address should be the same as your computer's IP address except for the last octet (e.g. if your computer is `192.168.1.7` the camera should be something like `192.168.1.225`).

If the camera is set to DHCP, it's likly not able to connect to the DCHP server (likely the router) on your network.
